' This file is used by Code Analysis to maintain SuppressMessage
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given
' a specific target and scoped to a namespace, type, member, etc.

Imports System.Diagnostics.CodeAnalysis

<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddFirearm.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddFirearm.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddFirearm.frmAddFirearm_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddFirearm.txtType_LostFocus1(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddFirearmClassification.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddFirearmClassification.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddGunSmithLog.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddGunSmithLog.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddGunSmithLog.frmAddGunSmithLog_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddMaintance.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddMaintance.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddMaintance.btnViewPlans_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddMaintance.frmAddMaintance_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddMaintancePlans.brnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddMaintancePlans.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddManufacturer.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddManufacturer.chkKTop_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddManufacturer.frmAddManufacturer_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddModel.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddModel.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddModel.chkKTop_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddModel.frmAddModel_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddNationality.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddNationality.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddNationality.frmAddNationality_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddPicture.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddPicture.btnBrowse_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddPicture.frmAddPicture_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddToWishList.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddToWishList.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddToWishList.frmAddToWishList_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAmmoCalc.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAmmoCalc.frmAmmoCalc_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCopyAccessory.btnCopy_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCopyAccessory.frmCopyAccessory_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCopyAccessory.GetFullName(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_EditSQL.btnSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_EditSQL.btnViewInReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_EditSQL.btnViewInReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_EditSQL.frmCR_EditSQL_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectColumns.btnGSQL_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectColumns.btnHideSQL_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectColumns.btnShowSQL_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectColumns.frmCR_SelectColumns_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrViewReport.frmCR_ViewReport_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrViewReport.frmCR_ViewReport_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0054:Use compound assignment", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmDbCleanup.AddToProgBar(System.String)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmDbCleanup.btnStart_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmDbCleanup.cbActionList_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmDbCleanup.frmDBCleanup_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditAccessory.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditAccessory.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditAccessory.frmEditAccessory_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditAmmunitionType.frmEditAmmunitionType_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditAmmunitionType.frmEditAmmunitionType_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditBarrelSystem.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditBarrelSystem.btnSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditBarrelSystem.frmEditBarrelSystem_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditCollectionDetails.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditCollectionDetails.btnUpdate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditCollectionDetails.chkBoxCR_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditCollectionDetails.frmEditCollectionDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditFirearmType.frmEditFirearmType_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmEditGunConditions.frmEditGunConditions_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditGunSmithLog.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditGunSmithLog.btnUpdate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditGunSmithLog.frmEditGunSmithLog_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmImportFirearm.btnImport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmImportFirearm.btnOpen_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmImportFirearm.frmImportFirearm_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.GlobalVars.Found(System.String,System.String)~System.Boolean")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AboutToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AddFirearmClassificationToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AddManufacturerToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AddMmunitionToMyCollectionToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AddPlaceOfOriginToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AddToWishlistToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AmmunitionCollectionReportToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BoundBook1ToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BoundBookToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BoundBookToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BoundBookVersion1ToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BoundBookVersion2ToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BounfBookVersion2ToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByAppraisedValueToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByAppraisedValueToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByInsuredValueToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByInsuredValueToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByPurchasedValueToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByPurchasedValueToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ClassificationToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.CleanUpToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.CopyFirearmToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.CustomReportToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.DocumentToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.EditToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.FirearmConditionsToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.FirearmTypesToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.GripTypesToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.GunToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ImportFirearmToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ListBox1_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.MDIParent1_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.PrintOutWishlistToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.QuickCollectionReportToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.QuickCollectionReportWNotesToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.RunSearch")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ShootersCardToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ShootersCardToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ShowNewForm(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton10_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton11_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton12_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton8_ButtonClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton9_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.tsslErrorsFound_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ViewDetailedReportToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ViewFullDetailedReportToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ViewToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.WishlistToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="type", Target:="~T:BSMyGunCollection.frmCR_EditSQL")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="type", Target:="~T:BSMyGunCollection.frmCR_SelectColumns")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddAccessory.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddAccessory.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddAccessory.frmAddAccessory_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddAmmo.frmAddAmmo_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddAmmoAudit.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddAmmoAudit.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddBarrelSystem.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddBarrelSystem.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddBarrelSystem.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddBarrelSystem.frmAddBarrelSystem_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddCollectionAmmo.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddCollectionAmmo.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddCollectionAmmo.frmAddCollectionAmmo_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectTable.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectTable.btnLoadSaved_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectTable.btnLoadSaved_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectTable.btnNext_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectTable.btnNext_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectTable.btnSQLEditor_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectTable.editReport")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectTable.editReport")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectTable.frmCR_SelectTable_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectTable.ShowSQLEditor")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="type", Target:="~T:BSMyGunCollection.frmCR_SelectTable")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrEditSql.btnSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrEditSql.btnViewInReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrEditSql.btnViewInReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrEditSql.frmCR_EditSQL_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectColumns.btnGSQL_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectColumns.btnHideSQL_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectColumns.btnShowSQL_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectColumns.frmCR_SelectColumns_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectTable.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectTable.btnLoadSaved_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectTable.btnLoadSaved_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectTable.btnNext_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectTable.btnNext_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectTable.btnSQLEditor_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectTable.EditReport")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectTable.frmCR_SelectTable_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrSelectTable.ShowSqlEditor")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAddAccess_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAddAccess_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAddAmmo_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAddAmmo_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAddDocument_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAddDocument_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAddExistingDoc_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAddExistingDoc_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAddMain_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAmmoReportByCal_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnAmmoReportByCal_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnExit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnGalleryReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnGalleryReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnGSLog_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnGSReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnPrintPreviewMaintanceReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnPrintPreviewMaintanceReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnPrintSale_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnPrintSale_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnRefresh_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnRefreshGS_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnRefreshPics_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnSold_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnSold_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnStolen_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnStolen_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnUnDoSale_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnVwAccessReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.btnVwAccessReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.Button3_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.DrawToScale(System.Drawing.Image,System.Int32,System.Int64)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.EditNotesToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.EditToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.EditToolStripMenuItem3_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.frmViewCollectionDetails_Disposed(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.frmViewCollectionDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0054:Use compound assignment", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.frmViewCollectionDetails_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.frmViewCollectionDetails_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.ListView1_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.mnuPicItem_Delete_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.mnuPicItem_Show_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.mnuPicItem_Show_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.MoveToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.RunEditMaintenance")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.ToolStripButton1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.ToolStripButton2_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.ToolStripButton5_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.ToolStripButton6_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.ToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.txtPurchasedFrom_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.txtPurchasedFrom_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmFirearmImagePicker.btnLeft_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmFirearmImagePicker.btnRight_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmFirearmImagePicker.frmFirearmImagePicker_Disposed(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmFirearmImagePicker.frmFirearmImagePicker_KeyDown(System.Object,System.Windows.Forms.KeyEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmFirearmImagePicker.frmFirearmImagePicker_KeyPress(System.Object,System.Windows.Forms.KeyPressEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmFirearmImagePicker.frmFirearmImagePicker_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmFirearmImagePicker.PictureBox1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmFirearmImagePicker.ProportionalSize(System.Drawing.Size,System.Drawing.Size)~System.Drawing.Size")>
<Assembly: SuppressMessage("Style", "IDE0054:Use compound assignment", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmFirearmImagePicker.ProportionalSize(System.Drawing.Size,System.Drawing.Size)~System.Drawing.Size")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSearchCollection.btnSearch_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSearchCollection.dgvResults_CellDoubleClick(System.Object,System.Windows.Forms.DataGridViewCellEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSearchCollection.frmSearch_Collection_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSearchCollection.ViewCollectionDetails")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditMaintenance.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditMaintenance.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditMaintenance.btnViewPlans_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditMaintenance.frmEditMaintenance_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditmanufactures.frmEditmanufactures_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditmanufactures.frmEditmanufactures_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditModel.EditToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditModel.frmEditModel_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditModel.frmEditModel_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditModelTypes.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditModelTypes.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditModelTypes.frmEditModelTypes_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditNationality.frmEditNationality_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditNationality.frmEditNationality_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditWishlist.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditWishlist.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditWishlist.frmEditWishlist_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmForgotPassword.btnAnswer_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmForgotPassword.frmForgotPassword_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmForSale.frmForSale_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmLogin.frmLogin_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmMoveBarrelConKit.btnAttach_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmMoveBarrelConKit.frmMoveBarrelConKit_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSettings.btnApply_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSettings.btnExit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSettings.btnSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSettings.chkNCCID_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSettings.frmSettings_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSold.btnApply_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSold.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSold.btnNA_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSold.btnUpdate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmSold.frmSold_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSDatabase.ConnExec(System.String)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSDatabase.GetData(System.String)~System.Data.DataTable")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSDatabase.sConnect~System.String")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSDatabase.sConnect~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSDatabase.sConnectOLE~System.String")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSDatabase.sConnectOLE~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSFileSystem.FileHasExtension(System.String)~System.Boolean")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSFileSystem.GetExtOfFile(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSFileSystem.GetNameOfFile(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSFileSystem.GetNameOfFileWOExt(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSFileSystem.GetPathOfFile(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSRegistry.GetLastWorkingDir~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSRegistry.GetRegSubKeyValue(System.String,System.String,System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0084:Use 'IsNot' expression", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSRegistry.GetSettings(System.String@,System.Boolean@,System.Int32@,System.Boolean@,System.Boolean@,System.Boolean@,System.Boolean@,System.Boolean@,System.Boolean@,System.Boolean@,System.Boolean@,System.Boolean@,System.Boolean@)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSRegistry.GetViewSettings(System.String,System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSRegistry.RegSubKeyExists(System.String)~System.Boolean")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.BSRegistry.SetSettingDetails")>
<Assembly: SuppressMessage("Style", "IDE0140:Object creation can be simplified", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.GlobalFunctions.AddDefaultPic(System.Int64)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.GlobalFunctions.FormatFromXML(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.GlobalFunctions.GetReportSQL(System.Int64)~System.String")>
<Assembly: SuppressMessage("Style", "IDE0140:Object creation can be simplified", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddPicture.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MGC.AutoFillCollections.MainCollectionDistinct(System.String,System.String)~System.Windows.Forms.AutoCompleteStringCollection")>
<Assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyGunCollection.DataGridPrinter._columnBounds")>
<Assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyGunCollection.DataGridPrinter._loggedInUsername")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.DataGridPrinter._GridPrintDocument_BeginPrint(System.Object,System.Drawing.Printing.PrintEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.DataGridPrinter._GridPrintDocument_BeginPrint(System.Object,System.Drawing.Printing.PrintEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.DataGridPrinter._GridPrintDocument_PrintPage(System.Object,System.Drawing.Printing.PrintPageEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.DataGridPrinter.DrawCellString(System.String,BSMyGunCollection.DataGridPrinter.CellTextHorizontalAlignment,BSMyGunCollection.DataGridPrinter.CellTextVerticalAlignment,System.Drawing.Rectangle,System.Boolean,System.Drawing.Graphics,System.Drawing.Font,System.Drawing.Brush)")>
<Assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.DataGridPrinter.RowsPerPage(System.Drawing.Font,System.Drawing.Graphics)~System.Int32")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.EditGunClassications.frmEditmanufactures_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddDocument.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddDocument.btnBrowse_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddDocument.frmAddDocument_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmAddDocument.InsertDoc(System.String)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAmmoInventory.frmViewAmmoInventory_Disposed(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAmmoInventory.frmViewAmmoInventory_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAmmoInventory.frmViewAmmoInventory_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAmmoInventory.ToolStripButton4_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAppraiserDetails.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAppraiserDetails.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAppraiserDetails.btnSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAppraiserDetails.frmViewAppraiserDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0140:Object creation can be simplified", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.DrawToScale(System.Drawing.Image,System.Int32,System.Int64)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewDocuments.AttachToFirearmToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewDocuments.EditToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewDocuments.frmViewDocuments_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewDocuments.OpenFile(System.String)")>
<Assembly: SuppressMessage("Style", "IDE0140:Object creation can be simplified", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewDocuments.SaveDocToDhh(System.Byte[],System.String)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewDocuments.ToolStripButton1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewGunSmithDetails.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewGunSmithDetails.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewGunSmithDetails.btnSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewGunSmithDetails.frmViewGunSmithDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewShopDetails.btnCancel_Click_1(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewShopDetails.btnEdit_Click_1(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewShopDetails.btnUpdate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewShopDetails.frmViewShopDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:BSMyGunCollection.DataGridPrinter._gridPrintDocument")>
<Assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyGunCollection.frmEditCollectionDetails._isSold")>
<Assembly: SuppressMessage("Style", "IDE0140:Object creation can be simplified", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCrViewReport.ToolStripButton3_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewBuyers.frmViewBuyers_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewBuyers.ListBox1_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("CodeQuality", "IDE0076:Invalid global 'SuppressMessageAttribute'", Justification:="<Pending>")>
<Assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmImportFirearm.ProcessXMLToDB_Details(System.String,System.String,System.String@,System.Int64@)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmLinkFromExistingDoc.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmLinkFromExistingDoc.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmLinkFromExistingDoc.frmLinkFromExistingDoc_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmStolen.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmStolen.btnSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmStolen.frmStolen_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmViewBuyerDetails.btnCanel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmViewBuyerDetails.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmViewBuyerDetails.btnUpdate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmViewBuyerDetails.frmViewBuyerDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewGrips.frmViewGrips_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewGrips.frmViewGrips_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewGunSmiths.frmViewGunSmiths_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewGunSmiths.ListBox1_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewMaintancePlan.brnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewMaintancePlan.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewMaintancePlan.btnUpdate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewMaintancePlan.frmViewMaintancePlan_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewMaintancePlanList.frmViewMaintancePlanList_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewPicture.frmViewPicture_Leave(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewPicture.frmViewPicture_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewPicture.frmViewPicture_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewPicture.GetPictureInfo(System.Int64,System.String@,System.String@)")>
<Assembly: SuppressMessage("Style", "IDE0054:Use compound assignment", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewPicture.ProportionalSize(System.Drawing.Size,System.Drawing.Size)~System.Drawing.Size")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewPicture.ProportionalSize(System.Drawing.Size,System.Drawing.Size)~System.Drawing.Size")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReport.frmViewReport_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReport.frmViewReport_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmViewReport_Ammo.frmViewReport_Ammo_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmViewReport_Ammo.frmViewReport_Ammo_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmViewReport_GunSmith.frmViewReport_GunSmith_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmViewReport_GunSmith.frmViewReport_GunSmith_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportAccessories.frmViewReport_Accessories_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportAccessories.frmViewReport_Accessories_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportAmmoByCaliber.frmViewReport_Ammo_By_Caliber_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportAmmoByCaliber.frmViewReport_Ammo_By_Caliber_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportBlankBoundBook.frmViewReport_Blank_BoundBook_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportBlankShootersCard.frmReport_Blank_ShootersCard_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportBlankShootersCard2.frmViewReport_Blank_ShootersCard2_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportBoundBook.frmViewReport_BoundBook_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportBoundBook.LoadData")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportBoundBook2.frmViewReport_BoundBook2_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportBoundBook2.LoadData")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportFirearmDetails.frmViewReport_FirearmDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportFirearmDetails.frmViewReport_FirearmDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportFirearmDetailsFullDetails.frmViewReport_FirearmDetailsFullDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportFirearmDetailsFullDetails.frmViewReport_FirearmDetailsFullDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportFirearmSaleInvoice.frmViewReport_FirearmSaleInvoice_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportFirearmSaleInvoice.GetData")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsurance.frmViewReport_Insurance_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsurance.frmViewReport_Insurance_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsuranceApprisedValue.frmViewReport_Insurance_ApprisedValue_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsuranceApprisedValue.frmViewReport_Insurance_ApprisedValue_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsuranceApprisedValueWTotal.frmViewReport_Insurance_ApprisedValue_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsuranceApprisedValueWTotal.frmViewReport_Insurance_ApprisedValue_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsuranceInsuredValue.frmViewReport_Insurance_InsuredValue_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsuranceInsuredValue.frmViewReport_Insurance_InsuredValue_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsuranceInsuredValueWTotal.frmViewReport_Insurance_InsuredValue_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsuranceInsuredValueWTotal.frmViewReport_Insurance_InsuredValue_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsuranceWTotal.frmViewReport_Insurance_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportInsuranceWTotal.frmViewReport_Insurance_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportMaintenance.frmViewReport_Maintenance_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportMaintenance.frmViewReport_Maintenance_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportPictures.frmViewReport_Pictures_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportPictures.frmViewReport_Pictures_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportQuickinvWDetailNotes.frmViewReport_Quickinv_w_DetailNotes_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportWishList.frmViewReport_WishList_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewReportWishList.frmViewReport_WishList_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmViewShops.frmViewShops_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmViewShops.ListBox1_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewWishList.frmViewWishList_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewWishList.frmViewWishList_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewWishList.ToolStripButton2_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="type", Target:="~T:BSMyGunCollection.frmViewReport_GunSmith")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="type", Target:="~T:BSMyGunCollection.frmViewShops")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditPicturedetails.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditPicturedetails.btnUpdate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditPicturedetails.frmEditPicturedetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmLinkDocToFirearm.btnAttach_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmLinkDocToFirearm.frmLinkDocToFirearm_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAmmoAuditList.frmViewAmmoAuditList_Disposed(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAmmoAuditList.frmViewAmmoAuditList_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAppraisers.frmViewAppraisers_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewAppraisers.ListBox1_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="type", Target:="~T:BSMyGunCollection.frmViewReport_Ammo")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyGunCollection.frmAddPicture.errOut")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.chkIsCompeition_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.chkNonLethal_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyGunCollection.frmAddPicture.errOut")>
<Assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification:="<Pending>", Scope:="member", Target:="~F:BSMyGunCollection.MGC.GlobalFunctions.MyClassName")>
<Assembly: SuppressMessage("Style", "IDE0054:Use compound assignment", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmViewCollectionDetails.GetPics")>
