' This file is used by Code Analysis to maintain SuppressMessage
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given
' a specific target and scoped to a namespace, type, member, etc.

Imports System.Diagnostics.CodeAnalysis

<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddFirearm.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddFirearm.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddFirearm.frmAddFirearm_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddFirearm.txtType_LostFocus1(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddFirearmClassification.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddFirearmClassification.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddGunSmithLog.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddGunSmithLog.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddGunSmithLog.frmAddGunSmithLog_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddMaintance.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddMaintance.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddMaintance.btnViewPlans_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddMaintance.frmAddMaintance_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddMaintancePlans.brnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddMaintancePlans.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddManufacturer.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddManufacturer.chkKTop_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddManufacturer.frmAddManufacturer_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddModel.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddModel.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddModel.chkKTop_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddModel.frmAddModel_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddNationality.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddNationality.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddNationality.frmAddNationality_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddPicture.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddPicture.btnBrowse_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddPicture.frmAddPicture_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddToWishList.btnAdd_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddToWishList.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAddToWishList.frmAddToWishList_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAmmoCalc.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmAmmoCalc.frmAmmoCalc_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmCopyAccessory.btnCopy_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmCopyAccessory.frmCopyAccessory_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmCopyAccessory.GetFullName(System.String)~System.String")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_EditSQL.btnSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_EditSQL.btnViewInReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_EditSQL.btnViewInReport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_EditSQL.frmCR_EditSQL_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectColumns.btnGSQL_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectColumns.btnHideSQL_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectColumns.btnShowSQL_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.frmCR_SelectColumns.frmCR_SelectColumns_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmCrViewReport.frmCR_ViewReport_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmCrViewReport.frmCR_ViewReport_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0054:Use compound assignment", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmDbCleanup.AddToProgBar(System.String)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmDbCleanup.btnStart_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmDbCleanup.cbActionList_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmDbCleanup.frmDBCleanup_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditAccessory.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditAccessory.btnEdit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditAccessory.frmEditAccessory_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditAmmunitionType.frmEditAmmunitionType_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditAmmunitionType.frmEditAmmunitionType_Resize(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditBarrelSystem.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditBarrelSystem.btnSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditBarrelSystem.frmEditBarrelSystem_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditCollectionDetails.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditCollectionDetails.btnUpdate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditCollectionDetails.chkBoxCR_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditCollectionDetails.frmEditCollectionDetails_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditFirearmType.frmEditFirearmType_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditGunConditions.frmEditGunConditions_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditGunSmithLog.btnCancel_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditGunSmithLog.btnUpdate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmEditGunSmithLog.frmEditGunSmithLog_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmImportFirearm.btnImport_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmImportFirearm.btnOpen_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.FrmImportFirearm.frmImportFirearm_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.GlobalVars.Found(System.String,System.String)~System.Boolean")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AboutToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AddFirearmClassificationToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AddManufacturerToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AddMmunitionToMyCollectionToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AddPlaceOfOriginToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AddToWishlistToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.AmmunitionCollectionReportToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BoundBook1ToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BoundBookToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BoundBookToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BoundBookVersion1ToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BoundBookVersion2ToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.BounfBookVersion2ToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByAppraisedValueToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByAppraisedValueToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByInsuredValueToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByInsuredValueToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByPurchasedValueToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ByPurchasedValueToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ClassificationToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.CleanUpToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.CopyFirearmToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.CustomReportToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.DocumentToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.EditToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.FirearmConditionsToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.FirearmTypesToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.GripTypesToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.GunToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ImportFirearmToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ListBox1_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.MDIParent1_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.PrintOutWishlistToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.QuickCollectionReportToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.QuickCollectionReportWNotesToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.RunSearch")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ShootersCardToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ShootersCardToolStripMenuItem1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ShowNewForm(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton1_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton10_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton11_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton12_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton8_ButtonClick(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ToolStripButton9_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.tsslErrorsFound_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ViewDetailedReportToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ViewFullDetailedReportToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.ViewToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:BSMyGunCollection.MdiParent1.WishlistToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="type", Target:="~T:BSMyGunCollection.frmCR_EditSQL")>
<Assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="type", Target:="~T:BSMyGunCollection.frmCR_SelectColumns")>
