'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.ComponentModel.Design
Imports System.Configuration
Imports System.Runtime.CompilerServices

Namespace My
    
    <CompilerGenerated(),  _
     GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     EditorBrowsable(EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <DebuggerNonUserCode(), EditorBrowsable(EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Object, e As EventArgs)
        If Application.SaveMySettingsOnExit Then
            Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <ApplicationScopedSetting(),  _
         DebuggerNonUserCode(),  _
         SpecialSetting(SpecialSetting.ConnectionString),  _
         DefaultSettingValue("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\MGC.mdb;Persist Security Info=True;Encrypt Password=False;Mask Password=False;Jet OLEDB:Database Password=14un0t2n0")>  _
        Public ReadOnly Property MGCConnectionString() As String
            Get
                Return CType(Me("MGCConnectionString"),String)
            End Get
        End Property
        
        <ApplicationScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("False")>  _
        Public ReadOnly Property App_UseRegistry() As Boolean
            Get
                Return CType(Me("App_UseRegistry"),Boolean)
            End Get
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewCollectionDetails_Height() As String
            Get
                Return CType(Me("ViewCollectionDetails_Height"),String)
            End Get
            Set
                Me("ViewCollectionDetails_Height") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewCollectionDetails_Width() As String
            Get
                Return CType(Me("ViewCollectionDetails_Width"),String)
            End Get
            Set
                Me("ViewCollectionDetails_Width") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewPicture_Height() As String
            Get
                Return CType(Me("ViewPicture_Height"),String)
            End Get
            Set
                Me("ViewPicture_Height") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewPicture_Width() As String
            Get
                Return CType(Me("ViewPicture_Width"),String)
            End Get
            Set
                Me("ViewPicture_Width") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewPicture_X() As String
            Get
                Return CType(Me("ViewPicture_X"),String)
            End Get
            Set
                Me("ViewPicture_X") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewPicture_Y() As String
            Get
                Return CType(Me("ViewPicture_Y"),String)
            End Get
            Set
                Me("ViewPicture_Y") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewCollectionDetails_X() As String
            Get
                Return CType(Me("ViewCollectionDetails_X"),String)
            End Get
            Set
                Me("ViewCollectionDetails_X") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewCollectionDetails_Y() As String
            Get
                Return CType(Me("ViewCollectionDetails_Y"),String)
            End Get
            Set
                Me("ViewCollectionDetails_Y") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewAmmoInv_Height() As String
            Get
                Return CType(Me("ViewAmmoInv_Height"),String)
            End Get
            Set
                Me("ViewAmmoInv_Height") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewAmmoInv_Width() As String
            Get
                Return CType(Me("ViewAmmoInv_Width"),String)
            End Get
            Set
                Me("ViewAmmoInv_Width") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewAmmoInv_X() As String
            Get
                Return CType(Me("ViewAmmoInv_X"),String)
            End Get
            Set
                Me("ViewAmmoInv_X") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewAmmoInv_Y() As String
            Get
                Return CType(Me("ViewAmmoInv_Y"),String)
            End Get
            Set
                Me("ViewAmmoInv_Y") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewAmmoadt_Height() As String
            Get
                Return CType(Me("ViewAmmoadt_Height"),String)
            End Get
            Set
                Me("ViewAmmoadt_Height") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewAmmoadt_Width() As String
            Get
                Return CType(Me("ViewAmmoadt_Width"),String)
            End Get
            Set
                Me("ViewAmmoadt_Width") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewAmmoadt_X() As String
            Get
                Return CType(Me("ViewAmmoadt_X"),String)
            End Get
            Set
                Me("ViewAmmoadt_X") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property ViewAmmoadt_Y() As String
            Get
                Return CType(Me("ViewAmmoadt_Y"),String)
            End Get
            Set
                Me("ViewAmmoadt_Y") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property frmFirearmImagePicker_Height() As String
            Get
                Return CType(Me("frmFirearmImagePicker_Height"),String)
            End Get
            Set
                Me("frmFirearmImagePicker_Height") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property frmFirearmImagePicker_Width() As String
            Get
                Return CType(Me("frmFirearmImagePicker_Width"),String)
            End Get
            Set
                Me("frmFirearmImagePicker_Width") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property frmFirearmImagePicker_X() As String
            Get
                Return CType(Me("frmFirearmImagePicker_X"),String)
            End Get
            Set
                Me("frmFirearmImagePicker_X") = value
            End Set
        End Property
        
        <UserScopedSetting(),  _
         DebuggerNonUserCode(),  _
         DefaultSettingValue("")>  _
        Public Property frmFirearmImagePicker_Y() As String
            Get
                Return CType(Me("frmFirearmImagePicker_Y"),String)
            End Get
            Set
                Me("frmFirearmImagePicker_Y") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <HideModuleName(),  _
     DebuggerNonUserCode(),  _
     CompilerGenerated()>  _
    Friend Module MySettingsProperty
        
        <HelpKeyword("My.Settings")>  _
        Friend ReadOnly Property Settings() As MySettings
            Get
                Return MySettings.Default
            End Get
        End Property
    End Module
End Namespace
